### ISSUE TITLE
ObjectMapperSupplier implementation never loaded

### ISSUE THREAD

**Issue by martinwithaar** [vladmihalcea/hibernate-types#35]
**Summary**
A custom `ObjectMapperSupplier` implementation is not loaded on startup.

**Steps to reproduce**
1. Create a custom `ObjectMapperSupplier` implementation that enables serialization features
2. Register the implementation with the `hibernate.types.jackson.object.mapper` setting in your `application.yml` file
3. Run the application

**Expected results**
The enabled serialization features are honored when retrieving json types from the database.

**Actual results**
The enabled serialization features are **not** honored when retrieving json types from the database.

---
## More info
When I add a `throw new RuntimeException();` in the implementation's `get()` method it fails to throw on startup so I know the body is never run.

My `application.yml` is as follows:
```yml
spring:
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        concurrency: 32
        max-concurrency: 48
        prefetch: 16
        acknowledge-mode: auto
        default-requeue-rejected: true
        retry:
          enabled: true
          multiplier: 2
          max-attempts: 10
          stateless: true
          initial-interval: 1s
          max-interval: 30s
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.generate_statistics: false
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.types.jackson.object.mapper: net.zuluconnect.ZuluconnectObjectMapperSupplier
      hibernate.jdbc.batch_size: 20
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 32
      maximum-pool-size: 48
      idle-timeout: 60000
```

A separate profile-based configuration `application-dev.yml` is also loaded:

```yml
spring:
  rabbitmq:
    host: "0.0.0.0"
    username: guest
    password: guest
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    hikari:
      username: root
      password:
logging:
  level:
    org: DEBUG

```

And my `ObjectMapperSupplier` implementation:

```java
package net.zuluconnect;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vladmihalcea.hibernate.type.util.ObjectMapperSupplier;

@SuppressWarnings("unused")
public class ZuluconnectObjectMapperSupplier implements ObjectMapperSupplier {

    @Override
    public ObjectMapper get() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, true);
        objectMapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
        objectMapper.configure(DeserializationFeature.USE_LONG_FOR_INTS, true);
        return objectMapper;
    }
}
```
