### ISSUE TITLE
Work with in-memory db (HSQLDB or H2)

### ISSUE THREAD

**Issue by milkchocolate** [vladmihalcea/hibernate-types#365]
Hi team,

I'm using HSQLDB and JPA ddl for running my app at local and unit tests(just for jpa implementations). 

When I have a json field in the repository entity, the ddl throws `org.hsqldb.HsqlException: type not found or user lacks privilege: JSON`. 

I understand that it's because the in-memory(HSQLDB) db doesn't support JSON as the column type.

I was wondering if there is a way to tell **hibernate-types** to use string for JPA ddl for the json fileds in repository entities

```yaml
spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:myDb;sql.syntax_mys=true
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
```

```java
@Type(type = "string")
@Column(name = "metadata", columnDefinition = "json")
val metadataNew: MetaData,
```
